### PR TITLE
feat: new packet types

### PR DESCRIPTION
**Pull request by zly2006**
To work together with litematica, should be merged after litematica stuff was built up

### CODE REVIEW

**Comment by zly2006** [comment]
servux side cde for https://github.com/sakura-ryoko/litematica/pull/3 is here.

**Comment by sakura-ryoko** [comment]
Is this all ready for review ?

**Comment by zly2006** [comment]
NOTE: This PR still need some improvements such as permission and rate limiting stuff, but if you want to help implement that stuff it is ready to merge

**Comment by sakura-ryoko** [comment]
> NOTE: This PR still need some improvements such as permission and rate limiting stuff, but if you want to help implement that stuff it is ready to merge

I have plans to add lucko permissions API for the various Data Provider's, and a config setting for allowing players to use them.

**Comment by sakura-ryoko** [comment]
Luck Permissions nodes added, and a "default permissions level", and added a new Config File handling for each Data Provider; so that they can individually restrict their use to a Permissions level (In addition to the Luck Perms nodes)

**Comment by sakura-ryoko** [comment]
Also, what do you mean by "rate limiting" ?  Like rate Limiting a packet ?

**Comment by zly2006** [comment]
> Also, what do you mean by "rate limiting" ? Like rate Limiting a packet or paste operations ?

Yes, because that might cause excessive network traffic, or server lag, so for example, the server only respond 10 nbt queries per tick, and the player can only paste 2 litematica in a second, etc.

**Comment by sakura-ryoko** [comment]
Okay I see

**Pull request merged**
