### PR TITLE
Easy placement v3 fix

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
I was just cleaning up stuff / making sure the code is the same.
I'll also have to update my Carpet PR, if they *ever* decide to even look at it.

**Comment by sakura-ryoko** [comment]
I'm going to make sure they are all equal code before merging.

**Comment by sakura-ryoko** [comment]
Unfortunately, we need to use 0.3.1 version because there was no intention of needing to update Servux.

**Comment by zly2006** [comment]
I think we should warn the server admins to update servux, for example, in discord. Because this version fixed a bed duping bug.

**Pull request merged**
