### PR TITLE
Feat: structure blacklst and whitelist

### PR DESCRIPTION
**Pull request by zly2006**
You dont need the old default permission stuff. You can just create a class for the config, with default values. it should be totally removed later.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
I was following the original JSON methodology from other mods.  Fortunately I am familiar with the GSON syntax, so I know what you are doing here.  But question, where are the `ServixConfig.class` files ?

**Comment by sakura-ryoko** [comment]
Ohh I see, it's an inner-class .

**Comment by sakura-ryoko** [comment]
Eventually I want to extend the `/servux` command like we talked about, with a Config Validator wrapper; sort of like how Carpet Mod works.

**Comment by zly2006** [comment]
> Eventually I want to extend the `/servux` command like we talked about, with a Config Validator wrapper; sort of like how Carpet Mod works, but lots of work needs to be done for this.
> 
> What I've done so far, was to lay out the frame work / ideas. The command interface is also meant to be converted into an extendable Interface for registering commands, for mods that use Servux as a server-side library mod, at some point.
> 
> Then perhaps in the future, the Data Provider's can be more of a 'module' system.

OK I ll do this in another PR

**Comment by sakura-ryoko** [comment]
I was also doing something with the whitelist / blacklist back in the 1.20.6 branch, but it was syncing the settings from the clients.  I removed all of that code previously for simplicity.

**Pull request merged**
